blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/YoDevStudio/ShauchMap/discussions
    about: Questions, ideas, and show-and-tell. Not sure if it's a bug? Start here.
